# yml版配置有问题。暂时原因未知。

# 默认配置，不指定profile则指启动这一个server。
spring:
  application:
    name: app-eureka-server
    
#server:
#  port: 1300
#eureka:
#  instance:
#    hostname: node0
#    # 指定instance-id会报错，不清楚原因暂时。
#    # instance-id: ${eureka.instance.hostname}:${server.port}
#  client:
#    serviceUrl:
#      # 默认指定自身
#      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
#    register-with-eureka: false
#    fetch-registry: false
#
#info:
#  server:
#    port: ${server.port}
#  eureka:
#    instance:
#      hostname: ${eureka.instance.hostname}
#      instance-id: ${eureka.instance.instance-id}   
#    client:
#      service-url:
#        default-zone: ${eureka.client.service-url.default-zone}
#      
