
server:
  port: 1302

eureka:
  instance:
    hostname: node2
    instance-id: ${spring.application.name}-${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      default-zone: http://node1:1301/eureka/
    register-with-eureka: true
    fetch-registry: true
      
    